kind: pipeline
type: kubernetes
name: default
clone:
  disable: true

steps:
  - name: clone
    image: wwma/drone-github-clone
    settings:
      SSH_KEY:
        from_secret: ssh_key

  - name: build
    image: golang:1.21.0-alpine
    depends_on: [clone]
    commands:
      - go env -w GOPROXY=https://goproxy.cn,direct
      - GOOS=linux GOARCH=amd64 go build -o main

  - name: publish
    depends_on: [ build ]
    image: plugins/docker
    pull: if-not-exists
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: nmtz/drone-github-clone
      tags:
        - latest
